In [74]:
import numpy as np
import pandas as pd
from keras.utils import np_utils
np.random.seed(10)
from keras.datasets import cifar10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

print('train:', len(x_train))
print('test:', len(x_test))

print(x_train.shape)
print(x_test[0][0][0])
print(y_test)

label_dict = {0:'airplane', 1:'automobile',2:'bird',3:'cat',4:'deer',5:'dog',6:'frog',7:'horse',8:'ship',9:'truck'}

x_train_normalize = x_train.astype('float32')/255
x_test_normalize = x_test.astype('float32')/255
print(x_test_normalize[0][0][0])

print(y_train.shape)
y_train[:6]

y_train_onehot = np_utils.to_categorical(y_train)
y_test_onehot = np_utils.to_categorical(y_test)

y_train_onehot[:5]

train: 50000
test: 10000
(50000, 32, 32, 3)
[158 112  49]
[[3]
 [8]
 [8]
 ...
 [5]
 [1]
 [7]]
[0.61960787 0.4392157  0.19215687]
(50000, 1)


array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [75]:
from keras.models import Sequential
from keras.layers import Dropout, Flatten, Conv2D, MaxPooling2D, Activation, ZeroPadding2D, Dense

In [76]:
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(3,3), padding='same', input_shape=(32,32,3), activation='relu')) #para: 3*3*3*32+32

In [77]:
model.add(Dropout(rate=0.25))

In [78]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [79]:
model.add(Conv2D(filters=64, kernel_size=(3,3), padding='same', activation='relu')) #para: 3*3*32*64+64 

In [80]:
model.add(Dropout(rate=0.25))

In [81]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [82]:
model.add(Flatten())

In [83]:
model.add(Dropout(rate=0.25))

In [84]:
model.add(Dense(1024, activation='relu'))  #para: 4096*1024+1024     4096 = 8*8*64

In [85]:
model.add(Dropout(0.25))

In [86]:
model.add(Dense(10,activation='softmax'))  #para: 1024*10+10

In [ ]:
print(model.summary())

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
train_history = model.fit(x=x_train_normalize, y=y_train_onehot, validation_split=0.2, epochs=10, batch_size=128, verbose=1)

In [ ]:
import matplotlib.pyplot as plt
def show_train_history(train_acc, test_acc):
    plt.plot(train_history.history[train_acc])
    plt.plot(train_history.history[test_acc])
    plt.title('Train history')
    plt.ylabel('Accuracy')
    plt.xlabel('Epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()

In [ ]:
show_train_history('accuracy', 'val_accuracy')

In [ ]:
show_train_history('loss', 'val_loss')

In [ ]:
scores = model.evaluate(x_test_normalize, y_test_onehot, verbose=0)
print()
print('accuracy = ', scores[1])

In [ ]:
prediction = model.predict_classes(x_test_normalize)

In [ ]:
prediction[:10]

In [ ]:
Predicted_Prob = model.predict(x_test_normalize)

In [ ]:
def show_Predicted_Prob(y, prediction, x_img ,x_predicted_prob, i):
    print('label: ', label_dict[y[i][0]], '    predict: ', label_dict[prediction[i]])
    plt.figure(figsize=(2,2))
    plt.imshow(np.reshape(x_test[i], (32,32,3)))
    plt.show()
    for j in range(10):
        print(label_dict[j]+' Probability:%1.9f'%(x_predicted_prob[i][j]))

In [ ]:
show_Predicted_Prob(y_test, prediction, x_test, Predicted_Prob, 1)

In [ ]:
prediction.shape

In [ ]:
y_test.shape

In [ ]:
y_test.reshape(-1)

In [ ]:
import pandas as pd
pd.crosstab(y_test.reshape(-1),prediction, rownames=['label'], colnames=['predict'])
#print(y_test_label)
#print(prediction)

In [ ]:
df = pd.DataFrame({'label':y_test, 'predict':prediction})
df[:20]

In [ ]:
df[(df.label!=df.predict)]